#!/bin/bash
echo ##################### Package
npm run-script build

echo ##################### Deploy
aws s3 sync build/ s3://origin.trackerp.xyz --acl public-read --profile dev1

echo ##################### Cloudfront
aws cloudfront create-invalidation --distribution-id E1FLKHXMXO0FKD --paths "/*"  --profile terransible

